export const FETCH_COUNTRY_REQUEST = "FETCH_COUNTRY_REQUEST";
export const FETCH_COUNTRY_SUCCESS = "FETCH_COUNTRY_SUCCESS";
export const FETCH_COUNTRY_FAILURE = "FETCH_COUNTRY_FAILURE";

export const FETCH_COUNTRY_BY_ID = "FETCH_COUNTRY_BY_ID";
export const FETCH_COUNTRY_BY_ID_SUCCESS = "FETCH_COUNTRY_BY_ID_SUCCESS";
export const FETCH_COUNTRY_BY_ID_FAILURE = "FETCH_COUNTRY_BY_ID_FAILURE";
